general.import = ["/Users/aniket/.config/alacritty/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM= "xterm-256color"

[font]
size= 14

[font.normal]
family= "UbuntuMono Nerd Font"

[window]
title = "valhalla"
opacity= 0.9
blur= true
option_as_alt = "Both"

[window.padding]
x= 10
y= 10

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[window.dimensions]
columns= 135
lines= 35
