general.import = ["/Users/aniket/.config/alacritty/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM= "xterm-256color"

[font]
size= 18

[font.normal]
family= "UbuntuMono Nerd Font"

[window]
decorations= "None"
opacity= 0.8
blur= true
option_as_alt = "Both"
startup_mode= "Fullscreen"

[window.padding]
x= 10
y= 10

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window.dimensions]
columns= 133
lines= 40
